language: ruby
rvm:
- 2.2
script:
- bundle exec jekyll build
after_success:
- git clone https://$GITHUB_REPO
- cd $(basename ${GITHUB_REPO%.git})
- git config user.name "Travis CI"
- git config user.email ${EMAIL}
- rsync -az --delete --exclude '.git*' ../_site/ .
- touch .nojekyll
- git add -A .
- git commit -m "Generated Jekyll site by Travis CI - ${TRAVIS_BUILD_NUMBER}"
- git push --force "https://${DEPLOY_KEY}@${GITHUB_REPO}" HEAD:${REPO_TARGET_BRANCH}
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GITHUB_REPO: github.com/msarm/ds.org.git
  - REPO_TARGET_BRANCH: gh-pages
  - secure: GODIbNiyAyBN0NpMFBr2utFl7UYblp9IruZL7EPIBoWMC9MHCducp3MBY6XXLbI5Bw9knFse2sE30Jph/4Bgn1VCGKFqZNjRN2RQUyEXsjmjcvqrZDkB8RQJBDGqJlLQMUjVoJjlx6DNjqiQg1aiKeY/bwSB7U9rOlzhWE+/1IJ/COqEhn28zm7pCfvnbgMYsqzUKa2kSRDiMk0Ygk4OD/3YA+sWv2Vupk64yTZioR7GTcGznQ0E3Y4sUDS1dJ+t5iMpApqK66x4dkv+JVRNUW0XG+FKIZCscM+IoFSsCneIVwOY+kCth6WBFoONmvitMxnBTo9/0v6SWcB6Xg32cePxNeSzY1DLcwrA3m94uWxGg1trkBb7UyBoqaHTouD9XHuty/B16erV4VUt+LEQ7vIg+fZNxr6vrvSvbZvdSdeGoNwUWF+KHjABxVmRMM7224V8MYpEBQX9Hdgi2QVIYaCsj5MAcZJiUFCah8kwEHoMvJdPA26uMe/zdrEuX4l/EAh7gWsocpVJi3mSPU3txiBmhRboJR3hH3HK0vyHfDPmS4457/p2rsM40FRslynYeffoKbap9I2stihfBGRCIfZRrpFuyOp8wgccz6/EKM9oKl22WhMXfaF7mzSnrzb2Usu3t2QzYL+TbAyOCzRQExUMpfaggvJZCdxi2MGcsNU=
  - secure: UO4yBfvaRS0frObshBGrTUUyhbMILWDMila/4/119468y0PCQ00SNQxtotH9tJE1I5HTw6ewijYrKkK7gFURRgjmwLaUUvdL3ipz5AYi6XR0OUxhLKGH6CFjxLwczyWqCmkzK4ndVk9qGn/H4wybZ/VarqpVfIwW6kkncZIthWVxjoYylF2ccoy9JuBRQBfCEi1wXxFJ3nBxv2ky+0wdOhNeNnXMec/U4Kk/OoFuwPD0KqNJC08psvw8Ch+/KuOB9jav+KO7vCzdfOfYjmT18RhXj/ElLfNI0MR/wAIoR/uszwN4W66xAe3fi2ha+ggFEs7PxDPsUvEi/p94GjpfH9PZzzeG+t51747Zm80HDpJnDaHiLAGR9bY2IHHYTxX9NT3C8CS/QRlWlR6SrIai7IJe3WQCtTEpG1urvLlXH+F9r5HHd39E8kjq5hntIeYEaR0bCDja3uWdZOvztWh/x1qKpGQvMbE0xT75ZhpimoOk8KxeDHdBG+3w0eHJyZU8rvZurrqkj7A7j1enmpHpCZ17twPr6bF6ediFupICxB9UP2fNzGPa6pXF4ZKgc9g7o4sLbSdCcwlhPclsJq0KrAI6mEttjOJaej1PFpsDsVFdW8mqlmNMf05rzJ/n4e2gkoDJnHyMR0KQUSa/lbaH8Y8hmspCD1yB8EWFVm555+s=
