# Site settings
title: dhanasai ACADEMY
email: mail@dhanasai.org
url: https://msarm.github.io/ds.org
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
skills: "Extra coaching for 10th & 12th class"
meta_author: LastName FirstName

# Google webmaster tools
google_verify: UA-71891881-1

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify: 8687E1380C3A475BC97265D76EFD65D4

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: MSarm
  location: Location
  social: Around the Web
  credits: Other Coaching

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/dhanasai.org
  - title: facebook
    url: http://facebook.com/dhanasai.org

# Postal address (add as many lines as necessary)
address:
  - line: Plot No#10, IIIrd Main Road Royalla Ngr,
  - line: Baghyalakshmi Nagar, Ramapuram, Chennai-89, TN.

# Credits content
credits: 'Hindi, drawing, etc. taken here.'

# Build settings
markdown: kramdown
permalink: pretty
